CREATE DATABASE SENAI_SPMEDGROUP_MANHA

USE SENAI_SPMEDGROUP_MANHA

CREATE TABLE TIPOS_USUARIOS (
	ID INT IDENTITY PRIMARY KEY,
	TIPO VARCHAR(20)
);

CREATE TABLE ESPECIALIZACAO (
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(50) UNIQUE NOT NULL
);

/*CREATE TABLE DOENCAS (
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(40) NOT NULL,
	DESCRICAO VARCHAR (500) 
);

Caso queira implementar futuramente

CREATE TABLE DOENCA_PACIENTE (
	ID_DOENCA INT FOREIGN KEY REFERENCES DOENCAS(ID),
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTES(ID)
);

*/

CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY,
	EMAIL VARCHAR(150) NOT NULL UNIQUE,
	SENHA VARCHAR(150) NOT NULL,
	ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPOS_USUARIOS(ID),
	DATA_NASCIMENTO DATETIME NOT NULL
);

CREATE TABLE PACIENTES (
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	CPF VARCHAR(30) NOT NULL UNIQUE,
	RG VARCHAR(30) NOT NULL UNIQUE,
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
);

CREATE TABLE PROGRESSO ( /*No caso do planejamento, ficou como status, mas status é reservado de SQL*/
	ID INT IDENTITY PRIMARY KEY,
	PROGRESSO VARCHAR(15) NOT NULL
);

/*
	Para futuras implementações kkk

CREATE TABLE CLINICAS (
	ID INT IDENTITY PRIMARY KEY,
	NOME_FANTASIA VARCHAR(100) NOT NULL,
	ENDERECO VARCHAR(150) NOT NULL,
	FUNCIONAMENTO VARCHAR(10) NOT NULL,
	RAZAO_SOCIAL VARCHAR(100) NOT NULL,
	CNPJ INT(100) NOT NULL UNIQUE
);*/

CREATE TABLE MEDICOS (
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	ESPECIALIZACAO INT FOREIGN KEY REFERENCES ESPECIALIZACAO(ID),
	CRM VARCHAR(30) NOT NULL,
	CNPJ VARCHAR(50) NOT NULL,
	/*ID_CLINICA INT FOREIGN KEY REFERENCES CLINICAS(ID)*/
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) UNIQUE
);

CREATE TABLE CONSULTA (
	ID INT IDENTITY PRIMARY KEY,
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTES(ID),
	ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID),
	/*ID_CLINICA INT FOREIGN KEY REFERENCES CLINICAS(ID)*/
	DATA_CONSULTA DATETIME NOT NULL,
	PROGRESSO INT FOREIGN KEY REFERENCES PROGRESSO(ID),
	OBSERVACAO VARCHAR (500),
);

/*DROP TABLE CONSULTA
DROP TABLE USUARIOS
DROP TABLE MEDICOS
DROP TABLE ESPECIALIZACAO
DROP TABLE PROGRESSO
DROP TABLE PACIENTES
DROP TABLE TIPOS_USUARIOS*/

/*INCRIVEL GAMBIARRA PRA FAZER O EXCEL E AS TABLES SINCRONIZAREM*/